export type Lot={slug:string;no:string;name:string;pedigree:string;type:"FOAL"|"EMBRYO";current:number;sex:string;year:string;image:string;description:string};
export const lots:Lot[]=[
{slug:"colestus-x-anita",no:"20",name:"Colestus x Anita",pedigree:"Colestus × Quick Star × Kannan",type:"EMBRYO",current:10000,sex:"Filly",year:"2027",image:"https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=1600&q=88",description:"An embryo from a proven international sport family. The dam line combines performance, scope and carefulness."},
{slug:"chacco-blue-x-usha",no:"18",name:"Chacco-Blue x Usha",pedigree:"Chacco-Blue × Kashmir van Schuttershof",type:"EMBRYO",current:14500,sex:"Colt",year:"2027",image:"https://images.unsplash.com/photo-1598974357801-cbca100e65d3?auto=format&fit=crop&w=1600&q=88",description:"A modern combination of two highly influential jumping bloodlines, selected for sport and breeding."},
{slug:"heartbreaker-x-emerald",no:"16",name:"Heartbreaker x Emerald",pedigree:"Heartbreaker × Emerald van 't Ruytershof",type:"EMBRYO",current:12500,sex:"Filly",year:"2027",image:"https://images.unsplash.com/photo-1551884831-bbf3cdc6469e?auto=format&fit=crop&w=1600&q=88",description:"A rare embryo combining proven Grand Prix blood with a strong Belgian maternal family."},
{slug:"comme-il-faut-x-emerald",no:"14",name:"Comme Il Faut x Emerald",pedigree:"Comme Il Faut × Emerald van 't Ruytershof",type:"FOAL",current:8500,sex:"Colt",year:"2026",image:"https://images.unsplash.com/photo-1534773728080-33d31da27ae5?auto=format&fit=crop&w=1600&q=88",description:"Athletic foal with a light-footed canter and an exceptional pedigree for the highest level of showjumping."},
{slug:"cornet-x-diamant",no:"11",name:"Cornet x Diamant",pedigree:"Cornet Obolensky × Diamant de Semilly",type:"FOAL",current:11000,sex:"Filly",year:"2026",image:"https://images.unsplash.com/photo-1551098891-7a1c852f6c6b?auto=format&fit=crop&w=1600&q=88",description:"Expressive filly with blood, balance and a direct dam line rich in international sport horses."},
{slug:"kashmir-x-for-pleasure",no:"08",name:"Kashmir x For Pleasure",pedigree:"Kashmir van Schuttershof × For Pleasure",type:"FOAL",current:7500,sex:"Colt",year:"2026",image:"https://images.unsplash.com/photo-1508343919546-4a5792fee935?auto=format&fit=crop&w=1600&q=88",description:"Powerful colt from a performance family, selected by Optimus for type, movement and pedigree."}
];
export const findLot=(slug:string)=>lots.find(l=>l.slug===slug);