import Link from "next/link";
import {Header,Footer} from "../components";
export default function Conditions(){return <><Header/><main className="legalPage"><div className="kicker">OPTIMUS ONLINE AUCTION</div><h1>CONDITIONS OF ONLINE AUCTIONS</h1><p className="legalIntro">Please read these conditions before registering or placing a bid. The reward bidding rules of this platform are explained separately below.</p><h2>1. GENERAL CONDITIONS OF ONLINE AUCTIONS</h2><ol>
<li>Stal Optimus Auction is organised by OPTIMUS AGRO NV, registered at Fortsesteenweg 17, 2860 Sint-Katelijne-Waver, Belgium.</li>
<li>All foals and embryos sold by Stal Optimus Auction are bred by Stal Optimus. No commission is charged.</li>
<li>Participation implies explicit acceptance of these auction conditions without reservation.</li>
<li>Buyers must register on this auction website before participating.</li>
<li>Buyers guarantee that registration information is correct and complete. Login credentials are strictly personal and may not be shared.</li>
<li>Sales are governed by Belgian law and awarded to the highest bidder, subject to payment of the settlement amount and applicable VAT. Bids and payments are in euros.</li>
<li>Each lot displays an indicative closing time. <strong>Important: the original conditions provided for a five-minute extension for bids placed in the final five minutes. The current platform's automatic extension must be aligned with this rule before live auctions.</strong></li>
<li>The highest bidder wins the lot. The settlement amount is the net winning bid (no commission), plus any applicable VAT (normally 21%). Stal Optimus issues an invoice.</li>
<li>VAT may be exempt for qualifying intra-community B2B deliveries outside Belgium with a valid EU VAT number, provided all legal conditions are met, or for qualifying exports outside the EU with valid transport and export documentation supplied within six months. Otherwise VAT will be charged.</li>
<li>After payment, buyer and seller arrange delivery. The buyer organises and pays for transport.</li>
<li>Ownership transfers after Optimus receives the buyer's payment.</li>
<li>Bids are irrevocable and unconditional. Each bidder is personally bound by bids made through their account. Joint bidders are jointly and severally liable. Stal Optimus may bid on behalf of third parties.</li>
<li>Stal Optimus determines the organisation and conduct of the auction, and may refuse bids, change or withdraw lots, suspend, extend, resume or cancel an auction where necessary, including in the event of technical problems. Internet auctions may experience technical imperfections.</li>
<li>Stal Optimus disclaims liability for visible or hidden defects to the extent permitted by applicable law. Any liability of Optimus Agro NV is limited to the amount paid by the buyer, subject to mandatory legal protections.</li>
<li>Belgian law applies. Disputes fall under the jurisdiction of the courts of Antwerp, subject to mandatory consumer jurisdiction rules.</li>
<li>Changes to these conditions may be published for subsequent auctions.</li>
<li>Stal Optimus disclaims liability relating to auctions and lots except where mandatory law or wilful misconduct prevents exclusion.</li>
</ol><h2>2. FOALS</h2><ol><li>All foals are checked by a veterinarian. The veterinary report is available on the individual foal page.</li><li>Risk transfers to the buyer on delivery of the foal to the buyer or transport company, subject to mandatory law.</li></ol><h2>3. IMPLANTED EMBRYOS — SURROGATE MARE</h2><ol><li><strong>LIVE FOAL GUARANTEE.</strong> The guarantee applies if pregnancy is lost through miscarriage or the foal is stillborn. Veterinary proof must be emailed within 24 hours to <a href="mailto:dries@dsf.be">dries@dsf.be</a>. In either case, the invoiced embryo amount is refunded. The surrogate mare guarantee is refunded on return of the mare to Optimus in accordance with the conditions below.</li><li>The surrogate mare remains the property of Optimus and must be returned by the buyer no later than six months after the foal's birth, healthy, dewormed and vaccinated. The mare may not be used for services other than raising the purchased foal. A refundable deposit of €2,000 excluding VAT applies. The buyer arranges and pays for return transport. Contact Optimus for terms if you wish to purchase the mare.</li><li>The foal's name must include the suffix “Optima” for a filly or “Optimus” for a colt, in combination with the buyer's stable name.</li><li>After the auction, Optimus' veterinarian rechecks all surrogate mares for pregnancy. If the mare is no longer pregnant, the sale is cancelled and Optimus is not obliged to provide a replacement embryo.</li></ol><h2>4. BID &amp; EARN REWARD RULES</h2><ol><li>For each accepted eligible bid before the final five-minute phase, the bidder earns a reward equal to 10% of the increase over the previous highest bid.</li><li>Earned rewards are retained when another bidder outbids you; rewards are not limited to the winning bidder.</li><li>During the final five-minute phase, bidding continues without a queue and no new rewards are earned. Rewards earned earlier remain recorded.</li><li>Before the final phase, bidders use the exclusive ten-second bidding queue. Each accepted bid and reward is recorded by the auction system.</li><li>Reward settlement and any applicable taxes are subject to the final published reward payment terms, which must be confirmed before the first live auction.</li></ol><div className="legalNote"><strong>Before the first live auction:</strong> These adapted conditions should be reviewed for Belgian legal compliance, particularly the reward programme, VAT, consumer protections and the auction extension rule.</div><p className="legalBack"><Link href="/">← BACK TO HOME</Link></p></main><Footer/></>}
